"""ClamAV daemon (clamd) lifecycle — start at app boot, stop on shutdown.

Why daemon mode? ``clamscan`` reloads the entire signature database (~300 MB)
on every invocation, which adds 5-15 s of fixed overhead per scan. ``clamd``
keeps the signatures in memory and ``clamdscan`` talks to it over a local
TCP socket, dropping per-scan overhead to ~milliseconds.

This module:

- Generates a minimal ``clamd.conf`` next to the bundled binaries (idempotent).
- Spawns ``clamd.exe`` as a daemon thread on first call to :func:`ensure_clamd_running`.
- Polls the TCP port until ``clamd`` is ready (returns once the daemon
  responds to PING, or gives up after a timeout).
- Exposes :func:`stop_clamd` for the lifespan shutdown hook.

Failure is non-fatal: if ``clamd`` can't start, the rest of the app keeps
working — :func:`pdf_safety.clamav_scan` falls back to the standalone
``clamscan`` binary.
"""

from __future__ import annotations

import socket
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

from core import logger

# State
_clamd_proc: subprocess.Popen[Any] | None = None
_clamd_ready = False
_clamd_lock = threading.Lock()
_clamd_host = "127.0.0.1"
_clamd_port = 3310  # ClamAV's default TCP port


def _bundled_clamav_dir() -> Path | None:
    """Return the bundled ``clamav/`` directory if present, else None."""
    here = Path(__file__).resolve().parent.parent
    cand = here / "clamav"
    if cand.is_dir():
        return cand
    return None


def _ensure_config(clamav_dir: Path) -> Path:
    """Write a minimal ``clamd.conf`` if missing. Returns its path.

    The conf binds to localhost TCP only (no Unix socket on Windows), points
    at the bundled signature database, and disables logging to file (we rely
    on stderr). Config is regenerated only when missing — an operator can
    edit it in place.
    """
    cfg_path = clamav_dir / "clamd.conf"
    log_dir = clamav_dir.parent / "_work" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "clamd.log"
    log_str = str(log_path).replace("\\", "/")
    if cfg_path.exists():
        return cfg_path
    cfg_path.write_text(
        "\n".join(
            [
                "# Auto-generated by Admin PDF Toolkit — edit if you know what you're doing.",
                "# clamd binds to loopback only; never expose this port.",
                # Relative path: clamd resolves against its --cwd (= clamav/)
                # — Windows clamd 1.x rejects absolute paths with a "no such
                # file" error even when they exist; relative works.
                "DatabaseDirectory database",
                f"LogFile {log_str}",
                "LogTime yes",
                "LogVerbose no",
                "LogFileMaxSize 5M",
                "PidFile " + log_str.replace("clamd.log", "clamd.pid"),
                "TCPSocket 3310",
                "TCPAddr 127.0.0.1",
                # Keep signatures hot, no idle reload
                "SelfCheck 600",
                "MaxThreads 4",
                # Limits to avoid pathological PDFs eating all RAM
                "MaxFileSize 200M",
                "MaxScanSize 400M",
                "MaxRecursion 10",
                "MaxFiles 10000",
                "ScanPDF yes",
                "ScanArchive yes",
                "",
            ]
        ),
        encoding="utf-8",
    )
    logger.info("clamd.conf generated at %s", cfg_path)
    return cfg_path


def _is_port_open(host: str, port: int, timeout: float = 0.4) -> bool:
    """Cheap TCP probe — returns True if something accepts on host:port."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            s.connect((host, port))
            return True
    except OSError:
        return False


def _ping_clamd(host: str, port: int, timeout: float = 1.0) -> bool:
    """Send PING to clamd and check for PONG response. Definitive readiness check."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            s.connect((host, port))
            s.sendall(b"nPING\n")
            data = s.recv(64)
            return b"PONG" in data
    except OSError:
        return False


def instream_scan(pdf_path: Path, timeout: float = 30.0) -> dict[str, Any] | None:
    """Scan a file via clamd's INSTREAM protocol over TCP.

    Bypasses ``clamdscan.exe`` entirely — avoids Windows ANSI/UTF-8 path
    encoding issues for filenames with non-ASCII characters (Turkish chars,
    etc) and the per-invocation subprocess startup cost. Returns ``None`` if
    clamd is not running. Otherwise returns the same dict shape as
    ``pdf_safety.clamav_scan`` (clean/threat/exit_code/engine/raw).

    Protocol per ClamAV manual:
      ``nINSTREAM\\n`` followed by repeated (uint32 BE size, payload) tuples,
      terminated by uint32 BE zero. Daemon replies with ``stream: OK`` or
      ``stream: <signature> FOUND`` on a single line.
    """
    if not _ping_clamd(_clamd_host, _clamd_port, timeout=0.5):
        return None
    import struct

    try:
        data = pdf_path.read_bytes()
    except OSError as e:
        return {
            "clean": True,
            "threat": None,
            "exit_code": -2,
            "engine": "clamd",
            "raw": f"read error: {e}",
        }

    chunk_size = 64 * 1024
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            s.connect((_clamd_host, _clamd_port))
            s.sendall(b"nINSTREAM\n")
            for i in range(0, len(data), chunk_size):
                chunk = data[i : i + chunk_size]
                s.sendall(struct.pack(">I", len(chunk)) + chunk)
            s.sendall(struct.pack(">I", 0))  # terminator
            resp_chunks: list[bytes] = []
            while True:
                p = s.recv(4096)
                if not p:
                    break
                resp_chunks.append(p)
            resp = b"".join(resp_chunks).decode("utf-8", errors="replace").strip()
    except TimeoutError:
        return {
            "clean": False,
            "threat": None,
            "exit_code": -1,
            "engine": "clamd",
            "raw": "timeout",
        }
    except OSError:
        return None  # connection lost — caller will fall back

    # Parse: "stream: OK" | "stream: <name> FOUND" | "stream: <error> ERROR"
    if "FOUND" in resp:
        # extract threat name
        threat: str | None = None
        line = resp.split("\n", 1)[0]
        # format: "stream: SIGNATURE_NAME FOUND"
        body = line.split(":", 1)[-1].strip()
        if body.endswith(" FOUND"):
            threat = body[:-6].strip()
        return {
            "clean": False,
            "threat": threat,
            "exit_code": 1,
            "engine": "clamd",
            "raw": resp[:1000],
        }
    if " OK" in resp:
        return {
            "clean": True,
            "threat": None,
            "exit_code": 0,
            "engine": "clamd",
            "raw": resp[:1000],
        }
    # Anything else → daemon error (signature mismatch, scan limit, etc).
    # Treat as INDETERMINATE — return None so caller falls back to standalone.
    return None


def ensure_clamd_running(boot_timeout: float = 25.0) -> bool:
    """Start clamd if not already up; return True when daemon answers PING.

    Idempotent: subsequent calls are a no-op. ``boot_timeout`` is the max
    time we wait for clamd to load the signature DB after spawn (typically
    8-15 s on first boot, ~3 s on warm cache).
    """
    global _clamd_proc, _clamd_ready

    with _clamd_lock:
        if _clamd_ready and _ping_clamd(_clamd_host, _clamd_port, timeout=0.5):
            return True

        # Maybe an external clamd is already up — try ping before spawning
        if _ping_clamd(_clamd_host, _clamd_port, timeout=0.5):
            logger.info("clamd already running on %s:%d (external)", _clamd_host, _clamd_port)
            _clamd_ready = True
            return True

        clamav_dir = _bundled_clamav_dir()
        if clamav_dir is None:
            logger.debug("clamd: bundled clamav/ directory not found")
            return False

        clamd_exe = clamav_dir / "clamd.exe"
        if not clamd_exe.exists():
            clamd_exe = clamav_dir / "clamd"  # Linux/macOS portable variant
        if not clamd_exe.exists():
            logger.debug("clamd: binary not found in %s", clamav_dir)
            return False

        # Database must be present — freshclam may still be running on cold boot
        db_files = list((clamav_dir / "database").glob("*.cvd")) + list(
            (clamav_dir / "database").glob("*.cld")
        )
        if not db_files:
            logger.info("clamd: signature DB missing yet (freshclam still running) — defer")
            return False

        cfg_path = _ensure_config(clamav_dir)

        try:
            # Hide console window on Windows
            creationflags = 0
            if hasattr(subprocess, "CREATE_NO_WINDOW"):
                creationflags = subprocess.CREATE_NO_WINDOW  # type: ignore[attr-defined]
            _clamd_proc = subprocess.Popen(
                [str(clamd_exe), "--config-file", str(cfg_path), "--foreground=true"],
                cwd=str(clamav_dir),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                creationflags=creationflags,
            )
            logger.info("clamd spawned (pid=%s), waiting for ready…", _clamd_proc.pid)
        except Exception as e:
            logger.warning("clamd spawn failed: %s", e)
            return False

        # Poll until PING succeeds or timeout
        deadline = time.time() + boot_timeout
        while time.time() < deadline:
            if _clamd_proc.poll() is not None:
                logger.warning("clamd exited prematurely (code=%s)", _clamd_proc.returncode)
                _clamd_proc = None
                return False
            if _ping_clamd(_clamd_host, _clamd_port, timeout=1.0):
                _clamd_ready = True
                logger.info(
                    "clamd ready on %s:%d after %.1fs",
                    _clamd_host,
                    _clamd_port,
                    boot_timeout - (deadline - time.time()),
                )
                return True
            time.sleep(0.5)

        logger.warning("clamd did not become ready within %.0fs", boot_timeout)
        return False


def is_ready() -> bool:
    """Quick, non-blocking readiness probe for callers that don't want to spawn."""
    return _clamd_ready and _ping_clamd(_clamd_host, _clamd_port, timeout=0.3)


def stop_clamd() -> None:
    """Politely terminate the daemon on app shutdown. Best-effort."""
    global _clamd_proc, _clamd_ready
    with _clamd_lock:
        if _clamd_proc is None:
            return
        try:
            # Send SHUTDOWN command via socket — clamd will exit cleanly
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.settimeout(2.0)
                    s.connect((_clamd_host, _clamd_port))
                    s.sendall(b"nSHUTDOWN\n")
            except OSError:
                pass
            try:
                _clamd_proc.wait(timeout=4.0)
            except subprocess.TimeoutExpired:
                logger.warning("clamd did not shut down cleanly, terminating")
                _clamd_proc.terminate()
                _clamd_proc.wait(timeout=2.0)
        except Exception as e:
            logger.debug("clamd stop error: %s", e)
        finally:
            _clamd_proc = None
            _clamd_ready = False
            logger.info("clamd stopped")


def find_clamdscan() -> str | None:
    """Locate ``clamdscan`` binary — bundled first, then PATH."""
    clamav_dir = _bundled_clamav_dir()
    if clamav_dir:
        for name in ("clamdscan.exe", "clamdscan"):
            cand = clamav_dir / name
            if cand.exists():
                return str(cand)
    import shutil

    return shutil.which("clamdscan")
